modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "heartfragmentore"
version = "${version}"
displayName = "Heart Fragment Ore"
authors = "Muluk"
description = '''
Add-on for Legendary Survival Overhaul that adds a new ore (normal & deepslate) which drops Heart Fragment.
'''
#logoFile = ""

[[dependencies.heartfragmentore]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.heartfragmentore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.heartfragmentore]]
modId="legendarysurvivaloverhaul"
mandatory=true
versionRange="[1.20.1-2.4.1,)"
ordering="NONE"
side="BOTH"
